# This file is part of XEmacs.

# Copyright (C) 2001, 2002 Steve Youngs

# XEmacs is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2, or (at your option) any
# later version.

# XEmacs is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# You should have received a copy of the GNU General Public License
# along with XEmacs; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

# Because of autoload issues, this strange sub directories needs to
# be maintained.  When adding new packages just put them at the end
# of the list.
PACKAGES= xemacs-base fsf-compat mail-lib dired efs apel \
	Sun edebug elib tooltalk xemacs-devel sounds-au sounds-wav \
	eieio build auctex crisp edt reftex texinfo textools tpu viper \
	vm w3 net-utils eudc footnote gnats mh-e supercite mailcrypt \
	rmail gnus tm mew zenirc bbdb cookie games mine \
	misc-games semantic cc-mode pcl-cvs ada c-support debug ediff \
	emerge idlwave jde prog-modes scheme sh-script vc-cc vc vhdl \
	xslt-process eterm igrep ilisp os-utils ps-print view-process \
	eshell pcomplete edit-utils speedbar calc calendar forms frame-icon \
	hm--html-menus ispell pc psgml sgml slider text-modes time \
	strokes tramp clearcase dictionary sieve ibuffer mmm-mode xslide \
	liece haskell-mode ess docbookide ecrypto ocaml sasl sml-mode

include ../iterate.rules
